### ISSUE TITLE
建议增加访问认证设置

### ISSUE THREAD

**Issue by ykfq** [snail007/shadowtunnel#1]
非常好，已经用起来了，配置也比SSR简单很多

为了方便家里和手机端使用，我把客户端配置到了一台国内的vps上，switchyOmega只要配置这个地址就能使用。

这样就有一个问题，如果别人知道了我的服务器地址或者客户端地址，就能随意的使用，这一点是非常不安全的，希望增加用户认证的功能。

**Comment by snail007** [comment]
这个和shadowtunnel没关系吧,它只是帮你建立tcp隧道，你说的验证是后端代理服务器的功能，请看你使用的代理服务器是否支持验证。如果是教程里面的proxy，它支持认证，可以看手册认证部分。
