### ISSUE TITLE
建议增加多后端负载均衡功能

### ISSUE THREAD

**Issue by ykfq** [snail007/shadowtunnel#2]
我现在有2个vps，都安装了goproxy 和shadowtunnel，我想要在本地局域网服务器上监听一个端口，然后能够通过隧道将流量转发到2台vps上。
我使用这个命令可以正常监听，但是日志显示只与其中一台建立了连接：
```
shadowtunnel -E -f 1.1.1.1:5000 -f 1.1.1.2:5000 -l :5000
```
当停掉建立连接的服务器上的服务时，流量并没有切换到另一台上。

**Comment by snail007** [comment]
现在不支持负载均衡
